it's a new year! happy new year. happy 2019.
Cleared out hella lots of stuff instead of doing work; panicked at the thought of summing up a year; removed references to our late cat.